feat(configmap): Add possibility to provide extra vars in configmap.
a5r0n/n8n-chart pull request #47
Opened 2024-09-06 14:05 UTC by abennani82

Hi,
PR de fix https://github.com/a5r0n/n8n-chart/issues/45 as requested. 
Thanks for review
Regards

2024-09-06 14:16 UTC, abennani82 commented
Can i add the ability to provide external secret ( for N8N_ENCRYPTION_KEY for example) to this PR or it has to be in a separate one?

2024-09-06 14:28 UTC, a5r0n requested changes
chart dependencies should be updated on different PR, (actually renovate will do)

2024-09-06 14:31 UTC, a5r0n commented
> Can i add the ability to provide external secret ( for N8N_ENCRYPTION_KEY for example) to this PR or it has to be in a separate one?

separate one please 🙏🏻

2024-09-09 18:48 UTC, abennani82 commented
Ok.
I’m waiting the validation of the first PR to send u the second one.

Aissam BENNANI


Le ven. 6 sept. 2024 à 16:31, a5r0n ***@***.***> a écrit :

> Can i add the ability to provide external secret ( for N8N_ENCRYPTION_KEY
> for example) to this PR or it has to be in a separate one?
>
> separate one please 🙏🏻
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/a5r0n/n8n-chart/pull/47#issuecomment-2334192259>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKCQC5XBHUDMSD5BKO54WVLZVG4F5AVCNFSM6AAAAABNYVCYMSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMZUGE4TEMRVHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-09 19:45 UTC, a5r0n commented on n8n/templates/configmap.yaml
> +  {{- with .Values.extraEnvs }}
Please check this @abennani82

2024-09-09 19:47 UTC, a5r0n reviewed
Can you remove the Chart.{yaml/lock} and dependent charts from this PR?

2024-09-10 06:34 UTC, abennani82 commented
I thaught it was already there.
I fix that

Aissam BENNANI


Le lun. 9 sept. 2024 à 21:47, a5r0n ***@***.***> a écrit :

> ***@***.**** commented on this pull request.
>
> Can you remove the Chart.{yaml/lock} and dependent charts from this PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/a5r0n/n8n-chart/pull/47#pullrequestreview-2290811573>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKCQC5SCOBZIHR3MYAGUAWDZVX3NFAVCNFSM6AAAAABNYVCYMSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOJQHAYTCNJXGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-13 09:05 UTC, abennani82 commented
Resources deleted

2024-10-17 15:18 UTC, abennani82 commented
Hi 
I’m not aware about pr GitHub process. Have y get changes from my pr ?

2024-12-19 01:15 UTC, a5r0n commented
@abennani82 you also deleted the charts them self, not just from the git commit..

2025-03-05 11:41 UTC, closed without merging